version: 2.1

orbs:
  snyk: snyk/snyk@2.1.0

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:22.2.0

jobs:
  security_scans:
    <<: *defaults
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
      - snyk/scan:
          command: code test --report --project-name=snyk-labs/github-actions-analyzer
          fail-on-issues: false
          monitor-on-build: false

  npm_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  CICD:
    jobs:
      - security_scans:
          name: Security Scans
          context:
            - security-labs-snyk
      - npm_test:
          name: Run npm test
